#This file builds the Docker images for a React/NodeJS application and runs it as microservices on Docker containers

#To ensure successful execution, clone this entire repository and execute this file while in the root folder of the cloned repository

#It's also a requirement to have Docker and the docker-compose plugin installed in your environment

#To launch this app without having to clone the entire repository,use the docker-compose.yaml file to run the app

version: "3.8"

services:
  # Frontend Service
  frontend_app:
    image: kelvinbavoke/frontend_app:latest
    container_name: frontend_app
    ports:
      - "80:3000"
    depends_on:
      - backend_app
    networks:
      - app-network
    stdin_open: true
    tty: true

  # Backend Service
  backend_app:
    image: kelvinbavoke/backend_app:latest
    container_name: backend_app
    ports:
      - "5000:5000"
    depends_on:
      - mongo_db
    environment:
      - MONGODB_URI=mongodb://mongo_db:27017/yolomy
    networks:
      - app-network
    restart: always
    stdin_open: true
    tty: true

  # MongoDB Service
  mongo_db:
    image: mongo
    container_name: mongo_db
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - app-network

# Shared Network
networks:
  app-network:
    driver: bridge

# Persistent Data Volume
volumes:
  mongo_data:
    driver: local
