---
- name: Deploy Full Stack Application Using Dockerized Roles
  hosts: all
  become: yes

  roles:
    - role: setup-docker
      tags: ["docker"]

    - role: setup-mongodb
      tags: ["mongodb"]

    - role: backend-deployment
      tags: ["backend"]

    - role: frontend-deployment
      tags: ["frontend"]