- name: Pull MongoDB image
  docker_image:
    name: "{{ mongo_image }}"
    source: pull

- name: Create custom bridge network if not exists
  docker_network:
    name: "{{ network_name }}"
    driver: bridge
    attachable: yes
  ignore_errors: yes

- name: Start MongoDB container
  docker_container:
    name: "{{ mongo_container_name }}"
    image: "{{ mongo_image }}"
    ports:
      - "{{ mongo_port }}:27017"
    volumes:
      - "{{ mongo_volume }}:/data/db"
    networks:
      - name: "{{ network_name }}"
    recreate: yes
