# manifests/mongo-service.yaml
apiVersion: v1
kind: Service
metadata:
  name: mongo-db
  namespace: ip-app
spec:
  selector:
    app: mongo
  ports:
    - protocol: TCP
      port: 27017
      targetPort: 27017
