- name: Pull backend image
  docker_image:
    name: "{{ backend_image }}"
    source: pull

- name: Start backend container
  docker_container:
    name: "{{ backend_container_name }}"
    image: "{{ backend_image }}"
    ports:
      - "{{ backend_port }}:5000"
    env:
      MONGODB_URI: "{{ mongo_connection_string }}"
    networks:
      - "{{ network_name }}"
    depends_on:
      - mongo_db
    recreate: yes
